service: ses-email-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    SNS_TOPIC_ARN: arn:aws:sns:${self:provider.region}:${aws:accountId}:${self:service}-${self:provider.stage}-ses-notifications
    
    REGION: ${self:provider.region}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendTemplatedEmail
        - ses:CreateTemplate
        - ses:DeleteTemplate
        - ses:UpdateTemplate
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: 
        - Fn::GetAtt: [SESNotificationTopic, TopicArn]

functions:
  handleBounce:
    handler: handler.handleSESNotification
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sns
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - ${self:service}-${self:provider.stage}-ses-notifications
          topicName: ${self:service}-${self:provider.stage}-ses-notifications

resources:
  Resources:
    SESNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-ses-notifications
    SESNotificationTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: ses.amazonaws.com
              Action: sns:Publish
              Resource: 
                Ref: SESNotificationTopic
        Topics:
          - Ref: SESNotificationTopic